version: '3.8'

services:
  frontend:
    build: ./React-Frontend
    image: salmatahaa/frontend-react:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - frontend-backend

  backend:
    build: ./DotNet-Backend
    image: salmatahaa/backend-dotnet-api:latest
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: mydb
      DB_USER: root
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    networks:
      - frontend-backend
      - backend-db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: mydb
    volumes:
      - db-data:/var/lib/mysql
    secrets:
      - db_password
    networks:
      - backend-db

networks:
  frontend-backend:
  backend-db:

volumes:
  db-data:

secrets:
  db_password:
    file: ./db_password.txt